version: '3.9'

services:
  db:
    container_name: mysqldb-gym
    image: mysql:8.1.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - mysql-net

  phpmyadmin:
    depends_on:
      - db
    container_name: phpmyadmin-gym
    image: phpmyadmin:5.2.1
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mysql-net

volumes:
  postgres-db:
    external: true

networks:
  mysql-net:
      